use std::fs::{self, File, OpenOptions};
use std::io::{Read, Seek, SeekFrom};
use std::path::{Path, PathBuf};

pub const MAX_BYTES: u64 = 32 * 1024 * 1024;

fn image_extension(header: &[u8]) -> Result<&'static str, String> {
    if header.starts_with(b"\x89PNG\r\n\x1a\n") {
        Ok("png")
    } else if header.starts_with(b"GIF87a") || header.starts_with(b"GIF89a") {
        Ok("gif")
    } else if header.starts_with(b"\xff\xd8\xff") {
        Ok("jpg")
    } else if header.starts_with(b"RIFF") && header.get(8..12) == Some(b"WEBP") {
        Ok("webp")
    } else if header.starts_with(b"BM") {
        Ok("bmp")
    } else {
        Err("wallpaper-unsupported".into())
    }
}

/// Stream into a new file, keeping the previous wallpaper on any failure.
/// `id` is generated by the caller, never supplied by the frontend.
pub fn import(source: &Path, base: &Path, id: &str) -> Result<PathBuf, String> {
    let mut input = File::open(source).map_err(|e| e.to_string())?;
    let metadata = input.metadata().map_err(|e| e.to_string())?;
    if !metadata.is_file() {
        return Err("wallpaper-unsupported".into());
    }
    if metadata.len() > MAX_BYTES {
        return Err("wallpaper-too-large".into());
    }
    let mut header = [0u8; 12];
    input.read_exact(&mut header).map_err(|e| e.to_string())?;
    let ext = image_extension(&header)?;
    input.seek(SeekFrom::Start(0)).map_err(|e| e.to_string())?;
    fs::create_dir_all(base).map_err(|e| e.to_string())?;
    let destination = base.join(format!("wallpaper.{id}.{ext}"));
    let mut output = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&destination)
        .map_err(|e| e.to_string())?;
    let result = (|| {
        // Bound the read too, in case the selected file grows during import.
        let copied = std::io::copy(&mut input.take(MAX_BYTES + 1), &mut output)
            .map_err(|e| e.to_string())?;
        if copied > MAX_BYTES {
            return Err("wallpaper-too-large".into());
        }
        output.sync_all().map_err(|e| e.to_string())
    })();
    drop(output);
    if let Err(error) = result {
        let _ = fs::remove_file(&destination);
        return Err(error);
    }
    Ok(destination)
}

/// Only discard old files after the new preferences are saved successfully.
pub fn cleanup(base: &Path, keep: &[&Path]) {
    if let Ok(entries) = fs::read_dir(base) {
        for entry in entries.flatten() {
            if entry
                .file_name()
                .to_string_lossy()
                .starts_with("wallpaper.")
                && !keep.contains(&entry.path().as_path())
            {
                let _ = fs::remove_file(entry.path());
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recognizes_content_regardless_of_file_extension() {
        for (bytes, ext) in [
            (b"\x89PNG\r\n\x1a\n".as_slice(), "png"),
            (b"GIF87a".as_slice(), "gif"),
            (b"GIF89a".as_slice(), "gif"),
            (b"\xff\xd8\xff".as_slice(), "jpg"),
            (b"RIFF1234WEBP".as_slice(), "webp"),
            (b"BM".as_slice(), "bmp"),
        ] {
            assert_eq!(image_extension(bytes).unwrap(), ext);
        }
        assert!(image_extension(b"not an image").is_err());
        assert!(image_extension(b"RIFF1234WAVE").is_err());
    }

    #[test]
    fn imports_preserve_old_file_and_cleanup_keeps_the_committed_one() {
        let base =
            std::env::temp_dir().join(format!("spiritbyte-wallpaper-test-{}", std::process::id()));
        fs::create_dir_all(&base).unwrap();
        let source = base.join("IMAGE.PNG");
        let bytes = b"GIF89a\x01\x00\x01\x00\x00\x00";
        fs::write(&source, bytes).unwrap();
        let previous = base.join("wallpaper.png");
        fs::write(&previous, b"previous").unwrap();
        let path = import(&source, &base, "first").unwrap();
        assert_eq!(path.extension().unwrap(), "gif");
        assert_eq!(fs::read(&path).unwrap(), bytes);
        assert_eq!(fs::read(&previous).unwrap(), b"previous");
        // A failed import must never remove or overwrite the working wallpaper.
        fs::write(&source, b"broken").unwrap();
        assert!(import(&source, &base, "second").is_err());
        File::create(&source)
            .unwrap()
            .set_len(MAX_BYTES + 1)
            .unwrap();
        assert_eq!(
            import(&source, &base, "large").unwrap_err(),
            "wallpaper-too-large"
        );
        assert!(previous.exists());
        cleanup(&base, &[&path]);
        assert!(path.exists());
        assert!(!previous.exists());
        assert!(source.exists());
        fs::remove_dir_all(base).unwrap();
    }
}
